### PR TITLE
Removed both network options from homescreen, and replaced with 'New …

### PR DESCRIPTION
**Pull request by chris24walsh**
…Game' and 'Load Game' options. Refactored the effect of those options - currently they both just start new game (i.e. load to space screen).

### CODE REVIEW

**Comment by chris24walsh** [comment]
Hey @samwiseguy7, just made a quick change. Was itching to start building up the proper game sequence (start new game, save game to savefile, load game from savefile, store planets in savefile etc.). Anyway, please review and merge :) So this is the first part of the sequence added - change the home screen options. If you don't have time, I'll just merge myself..

**Comment by chris24walsh** [comment]
Actually, I just went ahead and merged :D sorry @samwiseguy7 !!

**Comment by samwiseguy7** [comment]
Good. I'm just having lunch now but I'll be back around 1.

**Comment by samwiseguy7** [comment]
We'll need to chat about saving and loading - what way we want to do it.

**Pull request merged**
