### PR TITLE
Rename project from 'allegroTest' to 'SpaceHorse'

### PR DESCRIPTION
**Pull request by chris24walsh**
@zincsoda @samwiseguy7 What do you guys think? I'm leaning towards nicknaming the protagonist Space Horse, seeing as he is supposed to be a cargo delivery captain.

### CODE REVIEW

**Comment by zincsoda** [comment]
Perfect. Far better than 'allegro' :)

**Comment by samwiseguy7** [comment]
Horse sounds potentially grand (e.g. war horse, noble steed, white horse of
victory), but mule or donkey, there's no way to make that not sound like an
ass. So it depends on which set of connotations you prefer.

**Comment by samwiseguy7** [comment]
"Space Beast of Burden" lacks a certain pithiness.

**Comment by samwiseguy7** [comment]
Star horse is like a hero name though. Space ox sounds smelly. Space
friesian sounds agricultural.

**Comment by samwiseguy7** [comment]
You could go for the more general space ruminant, or even Space ungulate,
but then we risk ostracising the ignorant masses.

**Comment by chris24walsh** [comment]
@samwiseguy7...good to have your particular brand of dry, pedantic sacarsm onboard :) it wasn't the same without you.
But seeing as I've already refactored the entire project, maybe let's just stick with this. Could you guys pull this branch and test on yer dev envs before we merge this one in? @samwiseguy7 @zincsoda

**Comment by samwiseguy7** [comment]
If it works on yours I can get it to work on mine, so go ahead. I might
have time later on to test it.

**Pull request merged**
