### PR TITLE
Trade cargo

### PR DESCRIPTION
**Pull request by samwiseguy7**
I hope I'm doing this right.

### CODE REVIEW

**Comment by chris24walsh** [comment]
Unfortunately, I can't merge this now as I am working on a major code refactor which needs to be merged with develop first :( I'm rebuilding the project in an Object Oriented fashion. It will be worth it though! So...these new features you have added may need to be rewritten into the relevant class files :/

**Comment by samwiseguy7** [comment]
Yes, my coding was all pretty trivial stuff, and what you're doing takes
precedence. I can very easily add the features in the proper way once it's
sorted out.

**Comment by chris24walsh** [comment]
Thanks for understanding :) I don't want you to lose heart, I really appreciate your collaboration on this game! :D

**Comment by zincsoda** [comment]
I’m very interested now to take a look. Let us know when you have your new infrastructure in place Chris.

Dr. Steve Walsh
Chief Technology Officer, Secure Broadcast
M +44 (0) 7704206626
www.securebroadcast.com http://www.securebroadcast.com/

This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. Any views or opinions on this e-mail are solely those of the author and do not necessarily reflect any views or policies of Secure Broadcast. Secure Broadcast accepts no responsibility for changes to or interception of this email after it was sent or for any damage to the recipient's systems or data caused by this message or its attachments.

**Comment by chris24walsh** [comment]
Awesome! Great to have you on board Steve. I'm sure you will have lots of constructive criticism for my class architecture :)

**Comment by zincsoda** [comment]
My first constructive criticism is - avoid inheritance like the plague!

**Comment by chris24walsh** [comment]
Yep! Was gonna go down that road, but then realised the error of my ways. Component based architecture the way to go?

**Comment by zincsoda** [comment]
Focus on header files, interfaces and abstraction as much as possible. 
Keep your objects as independent as possible.
Even better - keep as few objects in memory as possible and don’t retain any state if possible.
Think about how you can write an object/class so that it has a single duty that could be called from a command line app if necessary.

That kind of thing :)

Dr. Steve Walsh
Chief Technology Officer, Secure Broadcast
M +44 (0) 7704206626
www.securebroadcast.com http://www.securebroadcast.com/

This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. Any views or opinions on this e-mail are solely those of the author and do not necessarily reflect any views or policies of Secure Broadcast. Secure Broadcast accepts no responsibility for changes to or interception of this email after it was sent or for any damage to the recipient's systems or data caused by this message or its attachments.

**Pull request closed without merging**
