### PR TITLE
Added animation class. For now it just is supposed to move the ship i…

### PR DESCRIPTION
**Pull request by chris24walsh**
…n a square formation, when the key A is pressed.

### CODE REVIEW

**Comment by chris24walsh** [comment]
@samwiseguy7 Have a look at this. Btw, from now on we ought to make a pull request every time we make a new feature branch, because it provides more visibility to the branch, plus we can add some continuous integration build tests and such later on :) Also, behold!
- [ ] Branch needs to achieve this, before it qualifies as complete..

Check boxes are good for focus :)

**Comment by chris24walsh** [comment]
Btw, this animation is broken. It causes the ships x/y coordinates to become undefined(or something?) and triggers a game over (??). Debugging should be fun :)

**Comment by chris24walsh** [comment]
Also, forgot to mention. The main reason for opening a pull request immediately after branch creation is to ensure we don't work away doing the same stuff, and then one of us has to scrap it :( i.e. it increases visibility on active branches and current work.

**Comment by samwiseguy7** [comment]
Sounds good. My comment (if I remember right, and I apologise for not putting the discussion here!) was that there were two separate ideas here. One is a function with detailed instructions of a certain path or actions for the ship to take, in cutscenes, for example. The second is a behaviour of the ship - i.e. the simple functions of the ship moving in a given direction, turning, exploding, whatever, and the corresponding updates necessary to the ship's current image for animation (e.g. a vector of allegro bitmap objects for each _different_ frame, plus an integer value, updated by the ship's behaviour, for the display to read to tell it which is the current frame).

My question is, okay, good idea starting pull requests when opening a new branch, but when do we decide to merge it? I suppose after having hashed it out in the discussion?

**Comment by chris24walsh** [comment]
Good ideas there, you could be right about including all of the ships movements into this class. But we'll see...

Yes, the idea is that I open the pull request after creating the new remote branch. Then when I feel its ready to merge, I will mention you in a comment to review and discuss. When you're happy, you merge it in. This is best practice :)

**Comment by samwiseguy7** [comment]
No, I'm thinking putting the ship's movements into the ship class. E.g. turn(signed integer numberTurns) { m_angle += 0.05_numberTurns; } and accelerate(signed integer numberSpeedChanges) { m_speed += 1_numberSpeedChanges; } The sign (+/-) tells the function whether the ship must turn left or right, or accelerate up or down (i.e. decelerate).

Then added to those functions could be a tick to a counter until the next frame in the animation (e.g. the rocket blasting), and when enough ticks are accumulated, the counter is flipped, and so the integer for the index of which bitmap from the vector that the display should select is incremented (or reset to the beginning). Or different functions of the ship will set the index for the current frame to something else.

So, I guess I still not convinced that the animation warrants its own class, because essentially it is a vector of allegro_bitmap objects and an integer to tell the display which index to draw from. If we made an "animation class" it would need to be versatile, i.e. able to be used by other things, not just the ship(s).

**Pull request merged**
